### ISSUE TITLE
How can I begin the second stage of training?

### ISSUE THREAD

**Issue by superFilicos** [nervjack2/MelHuBERT#4]
Hi !
         Thank you so much for your code and they are awesome. I 'm trying to use it on another dataset and we know that there are two stages in the training of Hubert. So how can I begin the second stage with your code ? By the way, what GPUs and how much time do you use to train them? Looking forward to your reply and thank again!

**Comment by nervjack2** [comment]
Hi !
In order to generate the stage-2 targets, basically, you would need to modify the code of fairseq. (clustering the hidden representation of stage-1)
https://github.com/facebookresearch/fairseq/tree/main/examples/hubert/simple_kmeans

I use a single 24GB Nvidia 3090. It requires about 150 hours to train on Librispeech 360-hour subset for 200 epochs.

**Comment by superFilicos** [comment]
Hello, thank for your answer!
          So, I should use the code in the link and my stage1 model to generate new "labels" and use your code to train a brand new model, is that true?

**Comment by superFilicos** [comment]
I mean, in the stage2 process I should train a new model instead of continue training on my stage1 model

**Comment by nervjack2** [comment]
Yes, you are right. You should train from scratch with the new labels instead of continue training. Actually, we have also tried continue training with the new labels in our paper, but it does not perform better.

**Comment by superFilicos** [comment]
OK, thank you so much! Have a good day!
